const serviceConfig = {
    "Laser" : [
    "date",
    "area",
    "skintype",
    "kj",
    "cost",
    "comments",
    ],
    "Makeup" : [
    "date",
    "area",
    "color_used",
    "technique",
    "cost",
    "comments",
    ],
    "Scalp" : [
    "date",
    "area",
    "pigment_used",
    "session_duration",
    "cost",
    "comments",
    ],
    "Skin" : [
    "date",
    "area",
    "type_of_pigmentation",
    "pulses",
    "cost",
    "comments",
    ],
    "Tattoo" : [
    "date",
    "area",
    "ink_used",
    "session_duration",
    "cost",
    "comments",
    ],
    "Chem-Peel" : [
    "date",
    "area",
    "type_of_peel",
    "duration",
    "cost",
    "comments",
    ],
    "Natural-Peel" : [
    "date",
    "area",
    "type_of_peel",
    "duration",
    "cost",
    "comments",
    ],
    "Microneedling" : [
    "date",
    "area",
    "needle_depth",
    "serum_used",
    "cost",
    "comments",
    ],
    "Facial" : [
    "date",
    "area",
    "products_used",
    "duration",
    "cost",
    "comments",
    ],
    "Sclerotherapy" : [
    "date",
    "area",
    "sclerosing_agent_used",
    "pulses",
    "cost",
    "comments",
    ],
    "Botox" : [
    "date",
    "area",
    "units_used",
    "technique",
    "cost",
    "comments",
    ],
    "Fillers" : [
    "date",
    "area",
    "product_used",
    "amount_used",
    "cost",
    "comments",
    ],
    "Microdermabrasion" : [
    "date",
    "area",
    "type_of_crystals_used",
    "duration",
    "cost",
    "comments",
    ],
    "Contouring" : [
    "date",
    "area",
    "technique",
    "session_duration",
    "cost",
    "comments",
    ],
    "Rejuvenation" : [
    "date",
    "area",
    "procedure",
    "duration",
    "cost",
    "comments",
    ]
}

export default serviceConfig
